### ISSUE TITLE
Special casing status codes

### ISSUE THREAD

**Issue by aesopwolf** [luin/superfetch#1]
Why are you special casing 2xx status codes?

``` js
if (code && code[0] === '2') {
  resolve(body);
} else {
  reject(res);
}
```

**Comment by luin** [comment]
When the status code begins with "2", it means the request is successful, and in this case, only the body part will be resolved to make people access the result easily. Otherwise, the request is considered to be failed, and the hole response including the status code will be rejected so people can know what's wrong with the request.

This default strategy makes superfetch very straightforward to use. For instance, in a Koa app:

``` javascript
var fetch = require('superfetch');
app.get("/users/:userId", function* (userId) {
  try {
    this.body = yield fetch.get("/users/" + this.params.userId);
  } catch (err) {
    this.status = err.statusCode;
    switch (this.status) {
    case 400:
      //...
    case 409:
      //...
    }
  }
});
```

However, you can change this strategy using the `transform` option if you don't like it :)
